### PR TITLE
Better positioning when it overflows the screen

### PR DESCRIPTION
**Pull request by hacdias**
- Fixes the instruction on the README which says to put 'middle' when it's 'center'
- When overflowing the screen by the right side, just align it so the window end is touching the end of the screen
- The same for the left side, and for y.

### CODE REVIEW

**Comment by hacdias** [comment]
Closing due to inactivity.

**Comment by pixtron** [comment]
Sorry @hacdias for my late reply. I was quite busy the last weeks.

I reviewed your PR, unfortunately it would remove a desired feature. But on the other hand i can see your use case. Therefore i suggest you adapt your PR, so the overflow positioning is configurable.

1.) opposite side (as it is now: default)
2.) screen edge (your suggestion)

I just fixed the README as you suggested.

**Comment by hacdias** [comment]
let me see then 😄

**Comment by hacdias** [comment]
@pixtron added the option `edge`. Also, I passed the code through the StandardJS linter. 😄 hope you don't mind.

**Comment by hacdias** [comment]
Ping @pixtron

**Pull request closed without merging**
